# Numpy Task of Varun Gupta

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("first_assignment.csv")
df

student_id             name  age  gender        department  marks_subject1  \
0           1         John Doe   18    Male  Computer Science              85   
1           2       Jane Smith   19  Female        Electrical              88   
2           3     Mary Johnson   18  Female        Mechanical              90   
3           4   James Williams   20    Male             Civil              75   
4           5   Patricia Brown   19  Female  Computer Science              92   
5           6    Michael Davis   18    Male        Electrical              80   
6           7  Jennifer Miller   19  Female        Mechanical              85   
7           8   William Wilson   20    Male             Civil              78   
8           9      Linda Moore   18  Female  Computer Science              88   
9          10    Robert Taylor   19    Male        Electrical              95   

   marks_subject2  marks_subject3  
0              78              92  
1              79              85  
2              88              76  
3              85              89  
4              91              83  
5              76              85  
6              82              90  
7              89              94  
8              84              78  
9              87              92

Q-1

In [3]:
arr_1 = np.array(df.marks_subject1)
arr_1

array([85, 88, 90, 75, 92, 80, 85, 78, 88, 95], dtype=int64)

Q-2

In [4]:
# Mean
mean = np.mean(arr_1)
print(mean)

# Median
median = np.median(arr_1)
print(median)

# Standard deviation
std = np.std(arr_1)
print(std)

85.6
86.5
6.019966777316965


Q-3

In [5]:
new_arr_1 = arr_1.reshape(2,5)
new_arr_1

array([[85, 88, 90, 75, 92],
       [80, 85, 78, 88, 95]], dtype=int64)

Q-4

In [6]:
new_arr_1[0,1]

88

Q-5

In [7]:
arr_1[:3]

array([85, 88, 90], dtype=int64)

Q-6

In [8]:
for i in range(0,len(arr_1)):
    arr_2 = arr_1[i] + 5
    print(arr_2)

90
93
95
80
97
85
90
83
93
100


Q-7

In [9]:
a = arr_1
b = 2
c = a*b
print(c)

[170 176 180 150 184 160 170 156 176 190]


Q-8

In [10]:
arr_3 = np.random.randint(10,100,size=(5,2))
arr_3

array([[12, 14],
       [27, 53],
       [71, 17],
       [40, 47],
       [84, 18]])

In [11]:
x = new_arr_1
y = arr_3
multi_arr = np.dot(x,y)
multi_arr

array([[20514, 12565],
       [20293, 12797]], dtype=int64)

Q-9

In [12]:
transpose = np.transpose(new_arr_1)
transpose

array([[85, 80],
       [88, 85],
       [90, 78],
       [75, 88],
       [92, 95]], dtype=int64)

Q-10

In [13]:
flatten = transpose.flatten()
flatten

array([85, 80, 88, 85, 90, 78, 75, 88, 92, 95], dtype=int64)

Q-11

In [14]:
arr_4 = np.array(df['marks_subject2'])
arr_4

array([78, 79, 88, 85, 91, 76, 82, 89, 84, 87], dtype=int64)

In [15]:
concat = np.concatenate((arr_1,arr_4))
concat

array([85, 88, 90, 75, 92, 80, 85, 78, 88, 95, 78, 79, 88, 85, 91, 76, 82,
       89, 84, 87], dtype=int64)

Q-12

In [16]:
np.unique(concat)

array([75, 76, 78, 79, 80, 82, 84, 85, 87, 88, 89, 90, 91, 92, 95],
      dtype=int64)

Q-13

In [17]:
filter_arr = []

for element in arr_1:
  if element > 80:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

new_arr_1 = arr_1[filter_arr]
print(new_arr_1)

[85 88 90 92 85 88 95]


Q-14

In [18]:
sorted = np.sort(arr_3)
sorted

array([[12, 14],
       [27, 53],
       [17, 71],
       [40, 47],
       [18, 84]])

Q-15

In [19]:
stacked_arr = np.stack((arr_1,arr_4),axis=0)
stacked_arr

array([[85, 88, 90, 75, 92, 80, 85, 78, 88, 95],
       [78, 79, 88, 85, 91, 76, 82, 89, 84, 87]], dtype=int64)

Q-16

In [20]:
splitted_arr = np.array_split(arr_1,2)
splitted_arr

[array([85, 88, 90, 75, 92], dtype=int64),
 array([80, 85, 78, 88, 95], dtype=int64)]

Q-17

In [21]:
arr_5 = np.array(df['marks_subject3'])
arr_5

array([92, 85, 76, 89, 83, 85, 90, 94, 78, 92], dtype=int64)

In [22]:
arr_5[arr_5 > 85] = 85
print(arr_5)

[85 85 76 85 83 85 85 85 78 85]


Q-18

In [23]:
arr_6 = np.random.randint(0,100,size =(1,10))
arr_6

array([[66,  1, 46, 22, 14, 93, 93, 90, 70, 70]])

Q-19

In [24]:
arr_6.mean()

56.5

Q-20

In [25]:
np.save('arr_1.npy', arr_1)
loaded_array = np.load('arr_1.npy')
loaded_array

array([85, 88, 90, 75, 92, 80, 85, 78, 88, 95], dtype=int64)