# Task 2 of Varun Gupta

# Q-1 Write a NumPy program to swap rows and columns of a given array in reverse order.

In [1]:
#importing numpy library
import numpy as np

#Creating Original Array
List_2D = [[1,2,3],[4,5,6],[7,8,9]]
matrix = np.array(List_2D)
print("The Original matrxix is: \n",matrix)

#Performing Operations to swap columns in reverse order
swap_columns = matrix[:,::-1]
print("The columnn edited matrix is: \n",swap_columns)

#Performing Operations to swap rows in reverse order
swap_rows = matrix[::-1,:]
print("The row edited matrix is: \n",swap_rows)

#The combination of both the matrix is displayed here
rev_matrix = matrix[::-1,::-1]
print("The edited matrix is: \n",rev_matrix)

The Original matrxix is: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The columnn edited matrix is: 
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
The row edited matrix is: 
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
The edited matrix is: 
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


# Q-2(a) - Write a NumPy program to find the most frequent value in an array.

array:
[6 9 5 1 4 6 7 8 9 8 7 1 7 5 1 0 1 5 5 0 8 9 0 7 0 7 6 5 1 1 9 5 3 8 7 9 
6 3 4 5 9 7 2 7 0 2 2 6]

In [2]:
#importing numpy library
import numpy as np
list_1 = [6, 9, 5, 1, 4, 6, 7, 8, 9, 8, 7, 1, 7, 5, 1, 0, 1, 5, 5, 0, 8, 9, 0, 7, 0, 7, 6, 5, 1, 1, 9, 5, 3, 8, 7, 9, 6, 3, 4, 5, 9, 7, 2, 7, 0, 2, 2, 6]
arr_1 = np.array(list_1)

# Used Unique function of numpy library to count the occurence of each value and recording it
value , occurence = np.unique(arr_1 , return_counts=True)

# Calculated the most frequent value using argmax() function
most_frequent_value = value[occurence.argmax()]
print("The most frequent value in the array is: ", most_frequent_value)

The most frequent value in the array is:  7


# (b)sort the frequent values in descending order

In [3]:
# The sorted array with frequent values in decending order is displayed here
sorted_arr_1 = value[occurence.argsort()[::-1]]
print("The sorted array(in decending order of frequencies) is displayed here: ",sorted_arr_1)

The sorted array(in decending order of frequencies) is displayed here:  [7 5 9 1 6 0 8 2 4 3]


# Q-3 Write a Pandas Program to create a dataframe such that the column labels are Name, Rollnumber, Subject1, Subject2 and Total

(i) Using Pandas function itself calculate the statistical summary(mean, median, mode, Quartiles, etc) of all the numerical columns.

In [4]:
#(i)

import numpy as np
import pandas as pd

# Create a DataFrame
data = {
    'Name': ['Varun', 'Vansh', 'Sohan', 'Rajesh', 'Yash'],
    'Rollnumber': [55 , 54 , 49 , 43 , 62],
    'Maths': [90, 80, 70, 95, 85],
    'JAVA': [85, 95, 80, 90, 75],
    'Total': [175, 175, 150, 185, 160]
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# Calculate statistical summary of numerical columns
print("\nStatistical Summary:")

print("Mean: \n")
print(df[[ 'Maths', 'JAVA', 'Total']].mean())

print("\nMedian: \n")
print(df[[ 'Maths', 'JAVA', 'Total']].median())

print("\nMode: \n")
print(df[[ 'Maths', 'JAVA', 'Total']].mode())

print("\nQuantiles: \n")
print(df[[ 'Maths', 'JAVA', 'Total']].quantile())

Original DataFrame:
     Name  Rollnumber  Maths  JAVA  Total
0   Varun          55     90    85    175
1   Vansh          54     80    95    175
2   Sohan          49     70    80    150
3  Rajesh          43     95    90    185
4    Yash          62     85    75    160

Statistical Summary:
Mean: 

Maths     84.0
JAVA      85.0
Total    169.0
dtype: float64

Median: 

Maths     85.0
JAVA      85.0
Total    175.0
dtype: float64

Mode: 

   Maths  JAVA  Total
0     70    75  175.0
1     80    80    NaN
2     85    85    NaN
3     90    90    NaN
4     95    95    NaN

Quantiles: 

Maths     85.0
JAVA      85.0
Total    175.0
Name: 0.5, dtype: float64


(ii) Sort the entire dataframe based on the alphabetical order.

In [5]:
#(ii)

# Sorting the DataFrame based on alphabetical order
df = df.sort_values(by='Name')
print("\nSorted DataFrame:")
print(df)


Sorted DataFrame:
     Name  Rollnumber  Maths  JAVA  Total
3  Rajesh          43     95    90    185
2   Sohan          49     70    80    150
1   Vansh          54     80    95    175
0   Varun          55     90    85    175
4    Yash          62     85    75    160


(iii) Change the dataset such that there are missing values and NAN values in the dataset and handle them appropriately.

In [6]:
#(iii)

# Introducing missing values and NaN values
df.loc[1, 'Maths'] = np.nan
df.loc[3, 'JAVA'] = np.nan

print("\nDataFrame with missing values:")
print(df)


# Handling missing values
df.fillna(0, inplace=True)  # Replace NaN with Absent

print("\nDataFrame after handling missing values:")
print(df)


DataFrame with missing values:
     Name  Rollnumber  Maths  JAVA  Total
3  Rajesh          43   95.0   NaN    185
2   Sohan          49   70.0  80.0    150
1   Vansh          54    NaN  95.0    175
0   Varun          55   90.0  85.0    175
4    Yash          62   85.0  75.0    160

DataFrame after handling missing values:
     Name  Rollnumber  Maths  JAVA  Total
3  Rajesh          43   95.0   0.0    185
2   Sohan          49   70.0  80.0    150
1   Vansh          54    0.0  95.0    175
0   Varun          55   90.0  85.0    175
4    Yash          62   85.0  75.0    160
